# ------------------------------------------------------------------------------
# Linken Container (Linkenc) Dockerfile version 2
# Using Bioconda to install latest packages instead compiling manually

# DO NOT USE THIS
# Abandoned on 2023/MAR/17 to due resolver conflicts and errors:
#    cutadapt can't be installed, problem installing xopen
#    picard mismatch java version (java is managed by mamba)

from debian:11 as base

ARG MAMBA_DIR=/usr/local/lib/mambaforge

RUN apt-get update \
    && apt-get install --assume-yes --quiet --no-install-recommends \
    curl apt-transport-https ca-certificates bzip2 \
    && update-ca-certificates \
    && curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-Linux-x86_64.sh --output mambaforge.sh \
    && bash mambaforge.sh -b -p /usr/local/lib/mambaforge \
    && source ${MAMBA_DIR}/etc/profile.d/conda.sh \
    && conda activate \
    && conda config --add channels defaults \
    && conda config --add channels bioconda \
    && conda config --add channels conda-forge \
    && conda config --set channel_priority strict \
    && mamba install --yes --channel bioconda bwa bwa-mem2 minimap2 htslib samtools picard \
    fastqc trim-galore lofreq bcftools nextflow --update-deps \
    && mamba install --yes nextflow

