[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lunar"
version = "0.0.1"
description = "lunar interface for linken container"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["lunar_cli"]

[project.scripts]
lunar = "lunar_cli.lunar:cli"
