#!/usr/bin/env python
# This is linken container entry script


## -----------------------------------------------------------------------------
linken_banner = r"""

  Linken Container (https://github.com/aixnr/linken)
  ==================================================

  This container image was generated by Docker and converted
  to Singularity Image Format using Apptainer.

  There are 3 subprograms available:

    - lunar, a utility script for preparing sequencing workflows
      $ linken lunar
    - hermes, for running the mapping and variant calling
      $ linken hermes -h
    - eevee, utility for analyzing mapped reads
      $ linken eevee

  Last compiled: 2024.DEC.15
"""


## -----------------------------------------------------------------------------
# main
if __name__ == "__main__":
    print(linken_banner)
