#!/usr/bin/env python
# This is linken container entry script


## -----------------------------------------------------------------------------
linken_banner = r"""

  Linken Container (https://github.com/aixnr/linken)
  ==================================================

  This container image was generated by Docker and converted
  to Singularity Image Format using Apptainer.

  There are 2 user-interface endpoints available:

    - lunar, a utility script for preparing sequencing workflows.
      $ linkenc lunar
    - hermes, for running the mapping and variant calling
      $ linkenc hermes -h
"""


## -----------------------------------------------------------------------------
# main
if __name__ == "__main__":
    print(linken_banner)
